apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ff-proxy.writer.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ff-proxy.labels" . | nindent 4 }}
data:
  REDIS_ADDRESS: {{ .Values.redisAddress }}
  READ_REPLICA: "false"
