---
version: "3"
services:

  proxy:
    image: "harness/ff-proxy:1.0.2"
    environment:
      DEBUG: "true"
      ACCOUNT_IDENTIFIER: ${ACCOUNT_IDENTIFIER}
      ORG_IDENTIFIER: ${ORG_IDENTIFIER}
      ADMIN_SERVICE_TOKEN: ${ADMIN_SERVICE_TOKEN}
      AUTH_SECRET: ${AUTH_SECRET}
      REDIS_ADDRESS: redis:6379
      API_KEYS: ${API_KEYS}
    ports:
      - 7000:${PORT:-7000}

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"