---
version: "3"
services:
  
  primary:
    image: "harness/ff-proxy:v2.0.0-rc.2"
    environment:
      PROXY_KEY: ${PROXY_KEY}
      READ_REPLICA: false
      AUTH_SECRET: ${AUTH_SECRET}
      REDIS_ADDRESS: redis:6379
      LOG_LEVEL: INFO
    ports:
      - ${PRIMARY_PORT:-7000}:7000
  
  replica0:
    image: "harness/ff-proxy:v2.0.0-rc.2"
    environment:
      LOG_LEVEL: INFO
      READ_REPLICA: true
      AUTH_SECRET: ${AUTH_SECRET}
      REDIS_ADDRESS: redis:6379
      LOG_LEVEL: INFO
    ports:
      - ${REPLICA0_PORT:-7001}:7000
  
  replica1:
    image: "harness/ff-proxy:v2.0.0-rc.2"
    environment:
      LOG_LEVEL: INFO
      READ_REPLICA: true
      AUTH_SECRET: ${AUTH_SECRET}
      REDIS_ADDRESS: redis:6379
      LOG_LEVEL: INFO
    ports:
      - ${REPLICA1_PORT:-7002}:7000

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
