service:
  name: feature_flag_relay_proxy
  identifier: feature_flag_relay_proxy
  orgIdentifier: Harness_Community
  projectIdentifier: Feature_Flags
  description: example service for deploying the relay proxy
  tags:
    source: harness-community/feature-flag-relay-proxy
  serviceDefinition:
    spec:
      manifests:
        - manifest:
            identifier: main
            type: K8sManifest
            spec:
              store:
                type: Github
                spec:
                  connectorRef: org.harness_community_github
                  gitFetchType: Branch
                  paths:
                    - kubernetes/feature-flag-relay-proxy.yaml
                  repoName: feature-flag-relay-proxy
                  branch: feat/pipeline
              valuesPaths:
                - kubernetes/values.yaml
              skipResourceVersioning: false
              enableDeclarativeRollback: false
      artifacts:
        primary:
          primaryArtifactRef: <+input>
          sources:
            - spec:
                connectorRef: org.harness_community_dockerhub
                imagePath: harness/ff-proxy
                tag: 1.0.2
                digest: ""
              identifier: main
              type: DockerRegistry
      variables:
        - name: port
          type: String
          description: sdk connection port
          required: true
          value: "7000"
        - name: replicas
          type: String
          description: number of pods
          required: true
          value: "2"
    type: Kubernetes
