namespace: <+infra.namespace>
app: <+service.name.toLowerCase().replace("_", "-").replace(" ", "-")>

image: <+artifact.image>
port: <+serviceVariables.port>
targetPort: <+serviceVariables.port>
serviceType: "NodePort"
replicas: <+serviceVariables.replicas>

accountId: <+account.identifier>
orgId: <+org.identifier>

adminServiceToken: <+secrets.getValue("ADMIN_SERVICE_TOKEN")>
authSecret: <+secrets.getValue("AUTH_SECRET")>
apiKeys:  <+secrets.getValue("API_KEYS")>
