namespace: <+infra.namespace>
app: <+service.name.toLowerCase().replace("_", "-").replace(" ", "-")>

image: <+artifact.image>
serviceType: <+serviceVariables.serviceType>

proxyKey: <+secrets.getValue("PROXY_KEY")>
authSecret: <+secrets.getValue("AUTH_SECRET")>

redisAddress: <+serviceVariables.redisAddress>
replicas: <+serviceVariables.replicas>
