# to create
namespace: <+infra.namespace>

# used for the name of the resources deployed
app: <+service.name.toLowerCase().replace("_", "-").replace(" ", "-")>

# default should be harness/ff-proxy:v2.0.0-rc.5 or latest rc version
image: <+artifact.image>

# spec for the service that will be exposed
service:
  type: <+serviceVariables.serviceType>
  port: <+serviceVariables.servicePort>
  # create a service for the writer proxy, not to be used by applications
  enableWriterService: <+serviceVariables.enableWriterService>

# how many read replicas to use
replicas: 2
  # min: <+serviceVariables.replicas>
  # max: <+serviceVariables.maxReplicas>
  # targetCPUUtilizationPercentage: <+serviceVariables.targetCPUUtilizationPercentage>

# proxy key from harness to configure the writer proxy
proxyKey: <+secrets.getValue("PROXY_KEY")>

# random string used for securing the connection from the sdks to the proxy
authSecret: <+secrets.getValue("AUTH_SECRET")>

# the connection url for the redis instance to use for storage
redisAddress: <+serviceVariables.redisAddress>

# INFO, DEBUG, WARNING, ERROR
logLevel: <+serviceVariables.logLevel>
